# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  cache: false
  globals:
    reisswolf_public_site_url: "%reisswolf_public_site_url%"
    reisswolf_public_store_url: "%reisswolf_public_store_url%"
    reisswolf_public_technical_service: "%reisswolf_public_technical_service%"

